### ISSUE TITLE
[BUG] Error in camelCased for certain files

### ISSUE THREAD

**Issue by stongef-sonepar** [mark-nicepants/figma2flutter#6]
### :information_source: Info

**Version: `v0.2.0`**

### :speech_balloon: Description

There's an issue with certain name in the application. It seems to be located in the string extension, expecially in the camelCased.<br />

```bash
figma2flutter --input ../Watts-Design-System/tokens/tokens.json --output lib/src/ui/
Unhandled exception:
RangeError (index): Invalid value: Valid value range is empty: 0
#0      _StringBase.[] (dart:core-patch/string_patch.dart:258:41)
#1      StringExtension.camelCased.<anonymous closure> (package:figma2flutter/extensions/string.dart:9:22)
#2      MappedListIterable.elementAt (dart:_internal/iterable.dart:415:31)
#3      ListIterable.join (dart:_internal/iterable.dart:165:22)
#4      StringExtension.camelCased (package:figma2flutter/extensions/string.dart:10:10)
#5      _getVariableName (package:figma2flutter/models/token.dart:320:26)
#6      new Token (package:figma2flutter/models/token.dart:23:39)
#7      TokenParser.findTokens (package:figma2flutter/token_parser.dart:87:21)
#8      TokenParser.findTokens (package:figma2flutter/token_parser.dart:106:11)
#9      TokenParser.findTokens (package:figma2flutter/token_parser.dart:106:11)
#10     TokenParser.findTokens (package:figma2flutter/token_parser.dart:106:11)
#11     TokenParser.findTokens (package:figma2flutter/token_parser.dart:106:11)
#12     TokenParser.findTokens (package:figma2flutter/token_parser.dart:106:11)
#13     TokenParser.parse (package:figma2flutter/token_parser.dart:41:22)
#14     _parseInput (file:///Users/fstonge/.pub-cache/hosted/pub.dev/figma2flutter-0.2.0-alpha/bin/figma2flutter.dart:124:49)
#15     main (file:///Users/fstonge/.pub-cache/hosted/pub.dev/figma2flutter-0.2.0-alpha/bin/figma2flutter.dart:66:20)
<asynchronous suspension>
```

**Comment by stongef-sonepar** [comment]
PR : #7

**Comment by stongef-sonepar** [comment]
Now part of PR : #4

**Comment by freemansoft** [comment]
Fixed by PR https://github.com/mark-nicepants/figma2flutter/pull/4
